In [5]:
import numpy as np
import pandas as pd
import glob
import os
from sklearn.feature_selection import VarianceThreshold

In [10]:
df = pd.read_csv('data_set/mercedes_benz/train.csv')

In [11]:
df

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [12]:
threshold = VarianceThreshold(threshold = 0.1)
from sklearn.model_selection import train_test_split

In [20]:
x = df.iloc[:,11:]
x

,X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,0,1,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4205,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4206,0,1,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4207,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4208,0,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0

In [21]:
y = df.iloc[:,1:2]
y

           y
0     130.81
1      88.53
2      76.26
3      80.62
4      78.02
...      ...
4204  107.39
4205  108.77
4206  109.22
4207   87.48
4208  110.85

[4209 rows x 1 columns]

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.03)

In [27]:
threshold = VarianceThreshold(threshold = 0.1)
threshold.fit(x_train)

VarianceThreshold(threshold=0.1)

In [28]:
sum(threshold.get_support())

85

In [31]:
constant_columns = [column for column in df.columns
                   if column not in df.columns[threshold.get_support()]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 378 but corresponding boolean dimension is 367